### ISSUE TITLE
Update dockerfiles to include up to date versions of tools

### ISSUE THREAD

**Issue by MarcPaquette** [cloudfoundry/capi-dockerfiles#13]
Some of the docker images are using older versions of some CLI tools.

There is a bot that is automatically bumping the bosh CLI, but not other tools such as `bbl`.

**Comment by MarcPaquette** [comment]
It may be worth looking into this:
https://www.starkandwayne.com/blog/how-to-download-the-latest-release-from-github/

**Comment by philippthun** [comment]
`bbl` is now also updated automatically.
